config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    collection do
      get :find_like
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  before_action :empty_flat
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  def find_like
    @flats = Flat.where("name LIKE ?", params[:search])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def empty_flat
    @empty_flat = Flat.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :picture %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <div class="d-flex">
    <%= f.submit class: "btn btn-primary m-1"%>
    <%= link_to 'Back', flats_path, class: "btn btn-danger m-1"%>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container align-middle w-50">
  <h1>Edit flat</h1>
  <%= render "form", flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1 class="font-weight-bold">All our Flats</h1>
  <p>All <%= @flats.count %> flats</p>
  <div class="row">
      <% @flats.each do |flat| %>
        <div class="col-4">
          <div class='card m-1'>
            <img src=<%= flat.picture %> alt="" class="card-img-top">
            <div class="card-body card-flat">
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card-text"><%= flat.address %></p>
              <div class="d-flex text-align-center">
                <i class="fas fa-users"></i>
                <p class="mr-2"><%= flat.number_of_guests %></p>
                <i class="fas fa-euro-sign"></i>
                <p><%= flat.price_per_night %></p>
              </div>
              <div class="d-flex">
                <%= link_to "More info", flat_path(flat), class: 'text-primary mr-3' %>
                <%= link_to "Edit", edit_flat_path(flat), class: 'text-warning mr-3' %>
                <%= link_to 'Remove',
                            flat_path(flat),
                            method: :delete,
                            data: { confirm: "Are you sure?" } %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container align-middle w-50">
  <h1>Add a new Flat</h1>
  <%= render "form", flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: url(<%= @flat.picture %>)"></div>
<!-- <img class="banner" src=<%= @flat.picture %> alt=""> -->
<div class="container w-75 justify-content-center margin-top-negative">
  <div class="d-flex justify-content-center">
    <div class="m-3 show-left">
      <div class="card-border">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div class="card-border p-3">
        <h2>A bit more about this flat...</h2>
        <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="m-3">
      <div class="card-border p-3">
        <p>Book this place!</p>
        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span><input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="card-border mt-2 p-3">
        <h2>Details</h2>
        <div class="d-flex text-align-center">
          <i class="fas fa-users"></i>
          <p class="mr-2"><%= @flat.number_of_guests %></p>
          <i class="fas fa-euro-sign"></i>
          <p><%= @flat.price_per_night %></p>
        </div>
      </div>
      <div class="d-flex justify-content-between card-border p-3">
        <p>Share</p>
        <ul class="list-inline d-flex font">
          <li class="m-1">
            <i class="fab fa-facebook"></i>
          </li>
          <li class="m-1">
            <i class="fab fa-twitter"></i>
          </li>
          <li class="m-1">
            <i class="fab fa-pinterest"></i>
          </li>
          <li class="m-1">
            <i class="fab fa-mail"></i>
          </li>

        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex m-0 p-0 w-100 justify-content-between bg-light mt-2">
      <%= link_to 'Simple Airbnb', flats_path, class: "navbar-button ml-2" %>
      <div class="d-flex">
        <form action="" class="d-flex">
          <div class="form-group">
            <input type="search" id="search" placeholder="Search" class="form-control">
          </div>
          <input type="submit" value="Search" class="btn btn-primary align-middle h-75 ml-2">
        </form>
        <%= link_to 'Add Flat', new_flat_path, class: "btn btn-primary  align-middle h-75 ml-2" %>
      </div>
    </div>
    </div>
    <%= yield %>
  </body>
</html>